import paramiko, time, sys
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('192.168.41.34', username='soporte', password='Soporte24', timeout=10)

print('=== Deploy fixes ===')
ssh.exec_command('cd /home/soporte/teko && git pull origin master 2>&1')
ssh.exec_command('cd /home/soporte/teko && docker compose build --no-cache teko-verify 2>&1 | tail -2')
ssh.exec_command('rm -rf /home/soporte/teko/admin/dist')
stdin, stdout, stderr = ssh.exec_command('cd /home/soporte/teko/admin && npm run build 2>&1')
sys.stdout.buffer.write(stdout.read())
ssh.exec_command('cd /home/soporte/teko && docker compose up -d --force-recreate teko-verify 2>&1')
time.sleep(20)
stdin, stdout, stderr = ssh.exec_command('curl -sI http://localhost:4400/admin-ui/ 2>/dev/null | head -3')
print('Admin UI:', stdout.read().decode())
ssh.close()
print('DONE')