import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const tekoNavigationConfig: NavigationTree[] = [
    {
        key: 'verificacion',
        path: '',
        title: 'Verificación',
        translateKey: '',
        icon: 'tekoDashboard',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'teko.dashboard',
                path: '/dashboard',
                title: 'Dashboard',
                translateKey: '',
                icon: 'tekoDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.sessions',
                path: '/sessions',
                title: 'Sesiones',
                translateKey: '',
                icon: 'tekoSessions',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.reviewQueue',
                path: '/review-queue',
                title: 'Cola de Revisión',
                translateKey: '',
                icon: 'tekoSessions',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.testVerify',
                path: '/test-verify',
                title: 'Probar Verificación',
                translateKey: '',
                icon: 'tekoTestVerify',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.ocrDebug',
                path: '/ocr-debug',
                title: 'Inspector OCR',
                translateKey: '',
                icon: 'tekoOcrDebug',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'administracion',
        path: '',
        title: 'Administración',
        translateKey: '',
        icon: 'PiUsersDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'teko.tenants',
                path: '/tenants',
                title: 'Tenants',
                translateKey: '',
                icon: 'tekoTenants',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.apps',
                path: '/apps',
                title: 'Apps',
                translateKey: '',
                icon: 'PiDesktopDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.team',
                path: '/team',
                title: 'Equipo',
                translateKey: '',
                icon: 'PiUsersDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.usage',
                path: '/usage',
                title: 'Uso y Métricas',
                translateKey: '',
                icon: 'tekoAudit',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.audit',
                path: '/audit',
                title: 'Auditoría',
                translateKey: '',
                icon: 'PiFileMagnifyingGlassDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.compliance',
                path: '/compliance',
                title: 'Cumplimiento',
                translateKey: '',
                icon: 'PiShieldCheckDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'configuracion',
        path: '',
        title: 'Configuración',
        translateKey: '',
        icon: 'PiGearDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'teko.workflows',
                path: '/workflows',
                title: 'Workflows',
                translateKey: '',
                icon: 'PiListChecksDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.questionnaires',
                path: '/questionnaires',
                title: 'Cuestionarios',
                translateKey: '',
                icon: 'PiListChecksDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.customization',
                path: '/customization',
                title: 'White Label',
                translateKey: '',
                icon: 'tekoCustomization',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.apiKeys',
                path: '/api-keys',
                title: 'API Keys',
                translateKey: '',
                icon: 'tekoApiKeys',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.webhooks',
                path: '/webhooks',
                title: 'Webhooks',
                translateKey: '',
                icon: 'PiShareNetworkDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.email',
                path: '/settings/email',
                title: 'Email / Mailing',
                translateKey: '',
                icon: 'PiEnvelopeDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.sms',
                path: '/settings/sms',
                title: 'SMS',
                translateKey: '',
                icon: 'PiPhoneDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.storage',
                path: '/settings/storage',
                title: 'Almacenamiento',
                translateKey: '',
                icon: 'PiHardDriveDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'guias',
        path: '',
        title: 'Guías',
        translateKey: '',
        icon: 'PiBookDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'guide.documentation',
                path: '/guide/documentation/introduction',
                title: 'Documentación',
                translateKey: '',
                icon: 'documentation',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'guide.sharedComponentDoc',
                path: '/guide/shared-component-doc/AbbreviateNumberDoc/Basic',
                title: 'Componentes Compartidos',
                translateKey: '',
                icon: 'sharedComponentDoc',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'guide.utilsDoc',
                path: '/guide/utils-doc/ClassNamesDoc/Basic',
                title: 'Utilidades',
                translateKey: '',
                icon: 'utilsDoc',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'guide.changelog',
                path: '/guide/changelog',
                title: 'Changelog',
                translateKey: '',
                icon: 'changeLog',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default tekoNavigationConfig