import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const tekoNavigationConfig: NavigationTree[] = [
    // ── 1. OPERACIÓN ──────────────────────────────────────────────────────────
    {
        key: 'operacion',
        path: '',
        title: 'Operación',
        translateKey: '',
        icon: 'tekoDashboard',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'teko.dashboard',
                path: '/dashboard',
                title: 'Dashboard',
                translateKey: '',
                icon: 'tekoDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.sessions',
                path: '/sessions',
                title: 'Sesiones',
                translateKey: '',
                icon: 'tekoSessions',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.reviewQueue',
                path: '/review-queue',
                title: 'Cola de Revisión',
                translateKey: '',
                icon: 'tekoSessions',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // ── 2. ORGANIZACIÓN ───────────────────────────────────────────────────────
    {
        key: 'organizacion',
        path: '',
        title: 'Organización',
        translateKey: '',
        icon: 'PiUsersDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'teko.tenants',
                path: '/tenants',
                title: 'Tenants',
                translateKey: '',
                icon: 'tekoTenants',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.apps',
                path: '/apps',
                title: 'Apps',
                translateKey: '',
                icon: 'PiDesktopDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.team',
                path: '/team',
                title: 'Equipo',
                translateKey: '',
                icon: 'PiUsersDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // Facturación: COLLAPSE (was a top-level TITLE, now nested)
            {
                key: 'org.facturacion',
                path: '',
                title: 'Facturación',
                translateKey: '',
                icon: 'PiCreditCardDuotone',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'billing.plans',
                        path: '/billing/plans',
                        title: 'Planes',
                        translateKey: '',
                        icon: 'PiCreditCardDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'billing.usageAlerts',
                        path: '/billing/usage-alerts',
                        title: 'Alertas de Uso',
                        translateKey: '',
                        icon: 'PiBellRingingDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'billing.invoices',
                        path: '/billing/invoices',
                        title: 'Facturas',
                        translateKey: '',
                        icon: 'PiReceiptDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'billing.paymentMethods',
                        path: '/billing/payment-methods',
                        title: 'Métodos de Pago',
                        translateKey: '',
                        icon: 'PiWalletDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },

    // ── 3. CONFIGURACIÓN ─────────────────────────────────────────────────────
    {
        key: 'configuracion',
        path: '',
        title: 'Configuración',
        translateKey: '',
        icon: 'PiGearDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            // Centro de Configuración (T5 — new view at /config-center)
            {
                key: 'teko.configCenter',
                path: '/config-center',
                title: 'Centro de Configuración',
                translateKey: '',
                icon: 'PiHouseDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // Verificación collapse: workflows + cuestionarios + reminders (gated)
            {
                key: 'config.verificacion',
                path: '',
                title: 'Verificación',
                translateKey: '',
                icon: 'PiListChecksDuotone',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'teko.workflows',
                        path: '/workflows',
                        title: 'Workflows',
                        translateKey: '',
                        icon: 'PiListChecksDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'teko.questionnaires',
                        path: '/questionnaires',
                        title: 'Cuestionarios',
                        translateKey: '',
                        icon: 'PiClipboardTextDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'teko.documentTypes',
                        path: '/document-types',
                        title: 'Documentos & Campos',
                        translateKey: '',
                        icon: 'tekoWorkflows',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'reminders.automated',
                        path: '/reminders/automated',
                        title: 'Recordatorios Automáticos',
                        translateKey: '',
                        icon: 'PiAlarmDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'reminders.scheduling',
                        path: '/reminders/scheduling',
                        title: 'Programación de Recordatorios',
                        translateKey: '',
                        icon: 'PiCalendarDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            // Comunicación collapse: email + templates + sms (gated)
            {
                key: 'config.comunicacion',
                path: '',
                title: 'Comunicación',
                translateKey: '',
                icon: 'PiEnvelopeDuotone',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'settings.email',
                        path: '/settings/email',
                        title: 'Email / Mailing',
                        translateKey: '',
                        icon: 'PiEnvelopeDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'settings.emailTemplates',
                        path: '/settings/email-templates',
                        title: 'Plantillas Email',
                        translateKey: '',
                        icon: 'PiEnvelopeSimpleDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'settings.sms',
                        path: '/settings/sms',
                        title: 'SMS',
                        translateKey: '',
                        icon: 'PiPhoneDuotone',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            // Marca
            {
                key: 'teko.customization',
                path: '/customization',
                title: 'Marca (White-label)',
                translateKey: '',
                icon: 'tekoCustomization',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // Configuración (Config Plane view — añadida en Fase 0)
            {
                key: 'teko.configuracion',
                path: '/configuracion',
                title: 'Configuración avanzada',
                translateKey: '',
                icon: 'PiSlidersHorizontalDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // ── 4. INTEGRACIONES ──────────────────────────────────────────────────────
    {
        key: 'integraciones',
        path: '',
        title: 'Integraciones',
        translateKey: '',
        icon: 'PiShareNetworkDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'integrations.connectors',
                path: '/integrations/connectors',
                title: 'Conectores',
                translateKey: '',
                icon: 'PiPlugsDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'integrations.oauth',
                path: '/integrations/oauth',
                title: 'OAuth',
                translateKey: '',
                icon: 'PiLockKeyDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'integrations.zapier',
                path: '/integrations/zapier',
                title: 'Zapier',
                translateKey: '',
                icon: 'PiZapDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.apiKeys',
                path: '/api-keys',
                title: 'API Keys',
                translateKey: '',
                icon: 'tekoApiKeys',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.webhooks',
                path: '/webhooks',
                title: 'Webhooks',
                translateKey: '',
                icon: 'PiShareNetworkDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.storage',
                path: '/settings/storage',
                title: 'Almacenamiento',
                translateKey: '',
                icon: 'PiHardDriveDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'integrations.providers',
                path: '/integrations/providers',
                title: 'Proveedores',
                translateKey: 'nav.integrations.providers',
                icon: 'plugZap',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // ── 5. CUMPLIMIENTO ───────────────────────────────────────────────────────
    {
        key: 'cumplimiento',
        path: '',
        title: 'Cumplimiento',
        translateKey: '',
        icon: 'PiShieldCheckDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'teko.compliance',
                path: '/compliance',
                title: 'Compliance normativo',
                translateKey: '',
                icon: 'PiShieldCheckDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.audit',
                path: '/audit',
                title: 'Auditoría',
                translateKey: '',
                icon: 'PiFileMagnifyingGlassDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.faceGallery',
                path: '/settings/face-gallery',
                title: 'Galería Facial',
                translateKey: '',
                icon: 'PiUsersThreeDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings.rateLimits',
                path: '/settings/rate-limits',
                title: 'Rate Limits',
                translateKey: '',
                icon: 'PiGaugeDuotone',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.usage',
                path: '/usage',
                title: 'Uso y Métricas',
                translateKey: '',
                icon: 'tekoAudit',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // ── 6. DEVELOPER ──────────────────────────────────────────────────────────
    {
        key: 'developer',
        path: '',
        title: 'Developer',
        translateKey: '',
        icon: 'PiCodeDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'teko.testVerify',
                path: '/test-verify',
                title: 'Probar Verificación',
                translateKey: '',
                icon: 'tekoTestVerify',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teko.ocrDebug',
                path: '/ocr-debug',
                title: 'Inspector OCR',
                translateKey: '',
                icon: 'tekoOcrDebug',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // ── 7. GUÍAS (Ecme template docs — sin cambios) ───────────────────────────
    {
        key: 'guias',
        path: '',
        title: 'Guías',
        translateKey: '',
        icon: 'PiBookDuotone',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'guide.documentation',
                path: '/guide/documentation/introduction',
                title: 'Documentación',
                translateKey: '',
                icon: 'documentation',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'guide.sharedComponentDoc',
                path: '/guide/shared-component-doc/AbbreviateNumberDoc/Basic',
                title: 'Componentes Compartidos',
                translateKey: '',
                icon: 'sharedComponentDoc',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'guide.utilsDoc',
                path: '/guide/utils-doc/ClassNamesDoc/Basic',
                title: 'Utilidades',
                translateKey: '',
                icon: 'utilsDoc',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'guide.changelog',
                path: '/guide/changelog',
                title: 'Changelog',
                translateKey: '',
                icon: 'changeLog',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default tekoNavigationConfig
