import {
    PiSpeedometerDuotone,
    PiListChecksDuotone,
    PiShieldCheckDuotone,
    PiFileMagnifyingGlassDuotone,
    PiUsersDuotone,
    PiDesktopDuotone,
    PiHardDriveDuotone,
    PiEnvelopeDuotone,
    PiPhoneDuotone,
    PiGearDuotone,
    PiBookDuotone,
    PiShareNetworkDuotone,
    PiToolboxDuotone,
    PiCodeDuotone,
    PiCircleHalfTiltDuotone,
    PiHouseLineDuotone,
    PiKeyDuotone,
    PiBellDuotone,
    PiBellRingingDuotone,
    PiPlugDuotone,
    PiFlashlightDuotone,
    PiUsersThreeDuotone,
    PiLaptopDuotone,
    PiFileDuotone,
    PiCurrencyCircleDollarDuotone,
    PiCreditCardDuotone,
    PiWalletDuotone,
    PiUserCircleDuotone,
    PiWarningDuotone,
    PiChatCircleDuotone,
    PiSpinnerGapDuotone,
    PiSpinnerBallDuotone,
    PiBoneDuotone,
    PiBreadDuotone,
    PiMedalDuotone,
    PiCardsDuotone,
    PiTableDuotone,
    PiTagDuotone,
    PiClockCountdownDuotone,
    PiChatCenteredDuotone,
    PiCheckSquareDuotone,
    PiClipboardTextDuotone,
    PiRowsDuotone,
    PiRowsPlusBottomDuotone,
    PiRadioButtonDuotone,
    PiChartDonutDuotone,
    PiListChecksBold,
    PiToggleRightDuotone,
    PiClockAfternoonDuotone,
    PiUploadDuotone,
    PiCaretCircleDownDuotone,
    PiListDuotone,
    PiCodeSimpleDuotone,
    PiFootprintsDuotone,
    PiBrowsersDuotone,
    PiChartLineUpDuotone,
    PiMapTrifoldDuotone,
    PiDotsThreeCircleDuotone,
    PiGridFourDuotone,
    PiCursorClickDuotone,
    PiTextAaDuotone,
    PiGaugeDuotone,
} from 'react-icons/pi'
import type { JSX } from 'react'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    // Teko Verify core
    tekoDashboard: <PiSpeedometerDuotone />,
    tekoSessions: <PiListChecksDuotone />,
    tekoTestVerify: <PiShieldCheckDuotone />,
    tekoOcrDebug: <PiFileMagnifyingGlassDuotone />,
    tekoTenants: <PiUsersDuotone />,
    tekoCustomization: <PiCircleHalfTiltDuotone />,
    tekoApiKeys: <PiKeyDuotone />,
    tekoAudit: <PiFileMagnifyingGlassDuotone />,

    // Navigation menu icon keys (by name)
    PiSpeedometerDuotone: <PiSpeedometerDuotone />,
    PiListChecksDuotone: <PiListChecksDuotone />,
    PiShieldCheckDuotone: <PiShieldCheckDuotone />,
    PiFileMagnifyingGlassDuotone: <PiFileMagnifyingGlassDuotone />,
    PiUsersDuotone: <PiUsersDuotone />,
    PiDesktopDuotone: <PiDesktopDuotone />,
    PiHardDriveDuotone: <PiHardDriveDuotone />,
    PiEnvelopeDuotone: <PiEnvelopeDuotone />,
    PiPhoneDuotone: <PiPhoneDuotone />,
    PiGearDuotone: <PiGearDuotone />,
    PiBookDuotone: <PiBookDuotone />,
    PiShareNetworkDuotone: <PiShareNetworkDuotone />,
    PiToolboxDuotone: <PiToolboxDuotone />,
    PiCodeDuotone: <PiCodeDuotone />,
    PiCircleHalfTiltDuotone: <PiCircleHalfTiltDuotone />,
    PiHouseLineDuotone: <PiHouseLineDuotone />,
    PiBellDuotone: <PiBellDuotone />,
    PiBellRingingDuotone: <PiBellRingingDuotone />,
    PiPlugDuotone: <PiPlugDuotone />,
    PiFlashlightDuotone: <PiFlashlightDuotone />,
    PiUsersThreeDuotone: <PiUsersThreeDuotone />,
    PiLaptopDuotone: <PiLaptopDuotone />,
    PiFileDuotone: <PiFileDuotone />,
    PiCurrencyCircleDollarDuotone: <PiCurrencyCircleDollarDuotone />,
    PiCreditCardDuotone: <PiCreditCardDuotone />,
    PiWalletDuotone: <PiWalletDuotone />,
    PiGaugeDuotone: <PiGaugeDuotone />,

    // Aliases for misspelled-but-used keys
    PiEnvelopesDuotone: <PiEnvelopeDuotone />,
    PiHardDiscDuotone: <PiHardDriveDuotone />,

    // Documentation / guide icons
    documentation: <PiBookDuotone />,
    sharedComponentDoc: <PiShareNetworkDuotone />,
    utilsDoc: <PiToolboxDuotone />,
    changeLog: <PiCodeDuotone />,
    accessDenied: <PiCircleHalfTiltDuotone />,
    landing: <PiHouseLineDuotone />,

    // UI Components (ecme docs)
    uiComponents: <PiGridFourDuotone />,
    common: <PiRowsDuotone />,
    uiCommonButton: <PiCursorClickDuotone />,
    uiCommonGrid: <PiGridFourDuotone />,
    uiCommonTypography: <PiTextAaDuotone />,
    uiCommonIcons: <PiRowsDuotone />,
    feedback: <PiWarningDuotone />,
    uiFeedbackAlert: <PiWarningDuotone />,
    uiFeedbackDialog: <PiChatCircleDuotone />,
    uiFeedbackProgress: <PiSpinnerGapDuotone />,
    uiFeedbackSkeleton: <PiBoneDuotone />,
    uiFeedbackSpinner: <PiSpinnerBallDuotone />,
    uiFeedbackToast: <PiBreadDuotone />,
    dataDisplay: <PiDesktopDuotone />,
    uiDataDisplayBadge: <PiMedalDuotone />,
    uiDataDisplayCard: <PiCardsDuotone />,
    uiDataDisplayTable: <PiTableDuotone />,
    uiDataDisplayTag: <PiTagDuotone />,
    uiDataDisplayTimeline: <PiClockCountdownDuotone />,
    uiDataDisplayTooltip: <PiChatCenteredDuotone />,
    forms: <PiListChecksDuotone />,
    uiFormsCheckbox: <PiCheckSquareDuotone />,
    uiFormsDatepicker: <PiClockCountdownDuotone />,
    uiFormsFormControl: <PiClipboardTextDuotone />,
    uiFormsInput: <PiRowsDuotone />,
    uiFormsInputGroup: <PiRowsPlusBottomDuotone />,
    uiFormsRadio: <PiRadioButtonDuotone />,
    uiFormsSegment: <PiChartDonutDuotone />,
    uiFormsSelect: <PiListChecksBold />,
    uiFormsSwitcher: <PiToggleRightDuotone />,
    uiFormsTimePicker: <PiClockAfternoonDuotone />,
    uiFormsUpload: <PiUploadDuotone />,
    navigation: <PiCaretCircleDownDuotone />,
    uiNavigationDropdown: <PiCaretCircleDownDuotone />,
    uiNavigationMenu: <PiListDuotone />,
    uiNavigationPagination: <PiCodeSimpleDuotone />,
    uiNavigationSteps: <PiFootprintsDuotone />,
    uiNavigationTabs: <PiBrowsersDuotone />,
    graph: <PiChartLineUpDuotone />,
    uiGraphChart: <PiChartLineUpDuotone />,
    uiGraphMaps: <PiMapTrifoldDuotone />,
    authentication: <PiShieldCheckDuotone />,
    others: <PiDotsThreeCircleDuotone />,
    dashboard: <PiSpeedometerDuotone />,
}

export default navigationIcon